filter:
  excluded_paths:
    - 'tests/'
    - 'vendor/'

build:
  dependencies:
    override:
      - composer require 'php:>=8.2' --no-install
      - composer require phpunit/phpunit:^9 --dev --update-with-all-dependencies --no-install
      - composer upgrade --no-interaction --prefer-dist
      - vendor/bin/phpunit --migrate-configuration
      - sed -i -E 's/executionOrder=".*?"/executionOrder="default"/' phpunit.xml.dist
  nodes:
    analysis: # see https://scrutinizer-ci.com/docs/tools/php/php-scrutinizer/
      environment:
        php:
          version: 8.2
      project_setup: { override: true }
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - command: php -dzend_extension=xdebug.so -dxdebug.mode=coverage vendor/bin/phpunit --verbose --testdox --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: clover
