filter:
    excluded_paths:
        - 'tests/'
        - 'vendor/'

build:
    nodes:
        analysis:
            tests:
                override:
                    - phpcs-run --standard=phpcs.xml.dist src/ tests/
                    - php-scrutinizer-run --enable-security-analysis

tools:
    external_code_coverage: true
