language: php

# php compatibility
php:
  - '7.2'
  - '7.3'
  - '7.4snapshot'

matrix:
  allow_failures:
    - php: '7.4snapshot'

# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

cache:
  - directories:
    - $HOME/.composer

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - mkdir -p build
  - vendor/bin/phplint
  - |
    if [[ "${FULLBUILD_PHP_VERSION}" == "${TRAVIS_PHP_VERSION}" ]]; then
      vendor/bin/php-cs-fixer fix --verbose
      vendor/bin/phpcbf --colors -sp src/ tests/
      php -dzend_extension=xdebug.so vendor/bin/phpunit --testdox --verbose --coverage-text --coverage-clover=build/tests/coverage.xml
      vendor/bin/phpstan.phar analyse --no-progress --level max src/ tests/
    else
      vendor/bin/phpunit --testdox --verbose
    fi

after_success:
  - |
    if [[ "${FULLBUILD_PHP_VERSION}" == "${TRAVIS_PHP_VERSION}" ]]; then
      mkdir -p build/ocular
      travis_retry composer require scrutinizer/ocular --working-dir=build/ocular --dev --no-interaction --prefer-dist
      build/ocular/vendor/bin/ocular code-coverage:upload --format=php-clover build/tests/coverage.xml
    fi

notifications:
  email: false
